export const sentences = [
	'The sun set over the mountains, casting a warm golden glow.',
	'he quickly realized that the key was missing from her bag.',
	'The cat curled up in the chair and fell fast asleep.',
	'He spent the afternoon organizing his bookshelf by color.',
	'The concert was loud and energetic, with the crowd singing along.',
	'The smell of freshly baked bread filled the entire house.',
	'They hiked up the trail, stopping occasionally to admire the view.',
	'The rain tapped gently on the windows as the storm rolled in.',
	'She smiled when she saw her favorite flowers blooming in the garden.',
	'The coffee shop was quiet, except for the sound of typing on laptops.',
	'The quick brown fox jumps over the lazy dog, but nobody knows where it was headed in such a hurry.',
	'She sells seashells by the seashore, hoping one day to save enough money for a trip around the world.',
	"A journey of a thousand miles begins with a single step, but it's the determination that keeps you going.",
	'Better late than never, as long as you learn from the experience and grow stronger for the next challenge.',
	'Every cloud has a silver lining, even if it takes time to see the good in a difficult situation.',
	'Actions speak louder than words, especially when those actions inspire others to follow your lead.',
	"Don't judge a book by its cover, because sometimes the most amazing stories are hidden inside plain exteriors.",
	"Practice makes perfect, but only if you're willing to put in the effort and accept failure along the way.",
	"Two wrongs don't make a right, and holding a grudge can weigh you down more than you realize.",
	"Time is money, but it's also one of the most precious resources you can never get back.",
	"You can't make an omelette without breaking eggs, so don't be afraid to take risks for something worthwhile.",
	'Beauty is in the eye of the beholder, but true beauty shines from within through kindness and compassion.',
	'A picture is worth a thousand words, but the story behind the image can sometimes mean even more.',
	'The early bird catches the worm, but sometimes the night owl has the advantage of a different perspective.',
	'When in Rome, do as the Romans do, but never forget your own values and beliefs wherever you go.',
	'The pen is mightier than the sword, especially when wielded by someone who knows how to use it wisely.',
	'A watched pot never boils, and waiting impatiently rarely brings about faster results.',
	"Absence makes the heart grow fonder, reminding us to appreciate the people we love when they're near.",
	'Honesty is the best policy, but delivering the truth with kindness is what makes it valuable.',
	"Don't bite the hand that feeds you, especially when loyalty and gratitude can take you further than resentment.",
	'Fortune favors the bold, but luck also smiles on those who are prepared for unexpected opportunities.',
	"Rome wasn't built in a day, and great things take time, effort, and a lot of patience to create.",
	"It's better to give than to receive, especially when giving brings joy to both the giver and the recipient.",
	'Knowledge is power, but wisdom is knowing how and when to use that knowledge for the greater good.',
	'Good things come to those who wait, but even better things come to those who work while they wait.',
	"The grass is always greener on the other side, until you realize that everyone's lawn requires maintenance.",
	"Curiosity killed the cat, but in the pursuit of knowledge, it's important to stay safe and be mindful.",
	'A penny saved is a penny earned, and financial discipline is key to achieving long-term goals.',
	"You can't judge a book by its cover, but first impressions can still make a lasting impact.",
	'The squeaky wheel gets the grease, but sometimes silence speaks louder than words when done strategically.',
	'Necessity is the mother of invention, driving innovation in the face of challenges and limitations.',
	"A rolling stone gathers no moss, but constant movement doesn't always lead to meaningful progress.",
	"Every dog has its day, and it's important to stay humble whether you're at your peak or in a valley.",
	'Haste makes waste, but thoughtful planning helps avoid unnecessary mistakes and wasted effort.',
	"Don't count your chickens before they hatch, because expectations can change when life takes unexpected turns.",
	'Out of sight, out of mind, but keeping in touch with those you care about helps strengthen relationships.',
	"No pain, no gain, but it's important to balance ambition with self-care to avoid burnout.",
	'The best things in life are free, but sometimes they require effort and attention to truly appreciate them.',
	'You reap what you sow, and the energy you invest in others often comes back to you in unexpected ways.',
	'A chain is only as strong as its weakest link, and teamwork relies on everyone contributing their best effort.',
	'A bird in the hand is worth two in the bush, but knowing when to take a risk is key to finding greater rewards.',
	'Slow and steady wins the race, especially when persistence and focus lead to long-term success.',
	"There's no place like home, but every new adventure offers lessons that help you grow and appreciate what you have.",
	"Beggars can't be choosers, but gratitude can turn even the smallest gift into something meaningful.",
	'The more, the merrier, but sometimes solitude is necessary to reflect and recharge.',
	"All's well that ends well, but the journey matters just as much as the destination in the end.",
	'Easier said than done, but action is what ultimately turns dreams into reality.',
	'Many hands make light work, but communication and coordination are essential for true collaboration.',
	"You can't have your cake and eat it too, but finding balance often requires thoughtful decision-making.",
	"An apple a day keeps the doctor away, but it's important to take care of both physical and mental health.",
	'Birds of a feather flock together, but diversity in thought and experience makes for stronger teams.',
	'A stitch in time saves nine, and solving small problems early can prevent bigger issues down the road.',
	"If it ain't broke, don't fix it, but continuous improvement is key to staying competitive.",
	'Too many cooks spoil the broth, but when roles are clearly defined, collaboration leads to great outcomes.',
	'The devil is in the details, and paying attention to the small things can make a big difference in success.',
	"Don't put all your eggs in one basket, and always have a backup plan to mitigate risk.",
	'A friend in need is a friend indeed, and true friendships are built on trust and support in hard times.',
	"Look before you leap, but don't let fear hold you back from taking calculated risks when necessary.",
	'Strike while the iron is hot, because timing is often crucial to success.',
	"Where there's smoke, there's fire, and being proactive can help prevent small issues from becoming bigger problems.",
	'A fool and his money are soon parted, but financial literacy can help avoid costly mistakes.',
	"Time flies when you're having fun, but make sure to savor the moments that matter most.",
	"Don't cry over spilled milk, and learn to let go of the things you cannot change.",
	'It takes two to tango, and collaboration is key to solving complex problems and achieving mutual success.',
	"You can't teach an old dog new tricks, but with an open mind, anyone can learn and grow at any age.",
	'Actions speak louder than words, but consistent follow-through is what builds credibility and trust.',
	'Blood is thicker than water, but friendships based on loyalty and respect can feel just as strong as family ties.',
	'The road to hell is paved with good intentions, so always ensure that your actions align with your principles.',
	"One man's trash is another man's treasure, and what we discard may hold value to someone else with a different perspective.",
	"The apple doesn't fall far from the tree, but each generation has the opportunity to forge its own path.",
	'What goes around comes around, and kindness given freely often finds its way back to the giver.',
	"Don't put off until tomorrow what you can do today, as procrastination can lead to missed opportunities.",
	'Practice what you preach, because living by example is the most powerful form of leadership.',
	"A picture paints a thousand words, but sometimes it's the stories we tell that leave the deepest impact.",
	"All that glitters is not gold, and appearances can be deceiving when you don't look beneath the surface.",
	'The proof is in the pudding, and results speak for themselves when it comes to demonstrating value.',
	'Variety is the spice of life, and embracing change and new experiences is key to personal growth.',
	'The grass is always greener on the other side of the fence, but contentment comes from appreciating what you have.',
	'Patience is a virtue, especially when the rewards are worth the wait and the effort required.',
	'Love is blind, but true love is built on mutual understanding, respect, and trust.',
	"A leopard can't change its spots, but personal growth is always possible with the right mindset.",
	'The bigger they are, the harder they fall, but resilience is what helps us rise again after failure.',
	'The ball is in your court, and taking responsibility for your actions is the first step toward achieving your goals.',
	"It's not rocket science, but even simple tasks require focus and attention to do them well.",
	"Let sleeping dogs lie, and sometimes it's best to leave certain issues in the past where they belong.",
	"Don't put the cart before the horse, and make sure your priorities are in order before moving forward.",
	'A house divided against itself cannot stand, and unity is essential for any team or family to thrive.',
	'Laughter is the best medicine, and a positive attitude can help you get through even the toughest challenges.',
	"There's no such thing as a free lunch, and everything of value comes at a cost, whether time, effort, or resources.",
	"Don't beat around the bush, and clear communication is key to avoiding misunderstandings and resolving conflicts.",
	"If you can't stand the heat, get out of the kitchen, but perseverance is often what separates success from failure.",
	"You can't have your cake and eat it too, but with smart planning, you can often find ways to balance competing priorities.",
	'The calm before the storm is a time to prepare, as challenges often come when you least expect them.',
	'A diamond in the rough, with a little polishing, can shine brighter than anyone ever imagined.',
	'Better safe than sorry, and taking precautions today can save you from bigger problems tomorrow.',
	"Ignorance is bliss, but knowledge is empowerment when you're prepared to face the truth.",
	'You win some, you lose some, but how you handle both success and failure defines your character.',
	"The best of both worlds is possible when you're willing to think creatively and explore different solutions.",
	'Two heads are better than one, and collaboration often leads to better ideas and stronger outcomes.',
	"Life is what happens when you're busy making other plans, so don't forget to enjoy the journey along the way.",
];
