[build]
  publish = "/build"
  command = "npm run build"

[functions]
  directory = "functions/"


[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "dist"
  functions = "functions/"